version: '3.4'

services:
  azure-function-app:
    build: .
    ports:
      - "8080:80"
    environment:
      - ENVIROMENT=Development
      - AzureFunctionsJobHost__Logging__Console__IsEnabled=true
      - AzureFunctionsJobHost__Logging__LogLevel__Default=Information
      - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - ServiceBusConnectionString=Endpoint=sb://
      - QueueName=myqueue
    depends_on:
      - azurite
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - mynetwork
 
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    ports:
      - "10000:10000" # Blob service port
      - "10001:10001" # Queue storage
      - "10002:10002" # Table storage
    volumes:
      - azurite_data:/data
    networks:
      - mynetwork

networks:
  mynetwork:
    name: mynetwork
    driver: bridge

volumes:
  azurite_data:
    external: false  
       
  